config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'home#about'

  get '/privacy' => 'home#privacy'

  resources :providers
  
  root to: 'home#search'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  acts_as_taggable
  validates :businessname, presence: true
  # validates :phonenumber, presence: true
  # validates_format_of :phonenumber, with: /\A\d\d\d(-|\s)?\d\d\d(-|\s)?\d\d\d\d\z/

  def self.search(query)
    where("businessname like ?", "%#{query}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search
    if params[:search]
      @provider = Provider.search(params[:search])
    end
  end

  def about
  end

  def privacy
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]


  def index
    if params[:search]
      @providers = Provider.search(params[:search])
    else
      @providers = Provider.all
    end
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:businessname, :firstname, :lastname, :phonenumber, :email, :street, :city, :state, :zip, :description, :url, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1>About Us</h1>
      <br/>
      <p class="text-justify">
        SunshineFamilyConnection.com is a place for Parents, Students and their Teachers to find resources in Pinellas County.
      </p>
      <p class="text-justify">
        We have information on many different types of services.
        You can find mentors and tutors here. You can also get help with mental health, after school
        activities, and social services - including child care, food, shelter and transportation.
      </p>
      <p class="text-justify">
        This initiative was made possible by the National Day of Civic Hacking St. Petersburg.
      </p>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/home/privacy.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-18">
      <h1>Privacy</h1>
      <br/>
      <p class="text-justify">
        We highly value the privacy of our users and their personal information. We will not share any personal information gathered through the site with anyone or any services.
      </p>
      <p class="text-justify">
        Sunshine Family Connection is a portal for those in need to connect with service providers. As such, we leave any exchange of information between users and services to the discretion of both parties. We do encourage all persons to be particularly careful with information that you may disclose over the phone or via email.
      </p>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/home/search.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-6 logo">
    	<%= image_tag "logo.png" %>
    </div>
    <div class="col-md-6">
      <h1>Connecting Families to the Services They Need</h1>
      <h2 class="tagline">A project of the St. Petersburg office of Education and Community Engagement</h2>
    </div>
  </div>

 </div>
 <div class="container-fluid">
  <div class="row">
    <div class="jumbotron">
    <div class="container">
      <section class="col-lg-12">
      <h3 class="searchSupport">Search For a Support Service</h3>
      <%= form_tag(providers_path, :method => "get", id: "search-form", class: "form-group") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Providers", class: "form-control" %>
        <%= submit_tag "Search", :businessname => nil, class: "btn btn-default" %>
      <% end %>
    </section>

    </div>
    </div>
  </div>
 <div class="container">
 <div class="row">
 <h3 class="directory">Search Directory by Category</h3>
 </div>
 <div class="row">
 <div class="col-md-4 col-sm-12 icon"><%= image_tag "icon-social.png" %></div>
 <div class="col-md-4 col-sm-12 icon"><%= image_tag "icon-education.png" %></div>
  <div class="col-md-4 col-sm-12 icon"><%= image_tag "icon-medical.png" %></div>
 </div>
 <div class="row">
 <div class="col-md-4 col-sm-12 services">
 <h4>Social Services</h4>
  <ul>
  <li>Childcare</li>
  <li>Food</li>
  <li>Shelter</li>
  <li>Transportation</li>
  </ul></div>
 <div class="col-md-4 col-sm-12 services">
 <h4>Educational</h4>
  <ul>
  <li>Tutoring
  <li>Mentoring
  <li>ESL
  <li>Special Needs Kids</li>
</div>
  <div class="col-md-4 col-sm-12 services">
   <h4>Health Services</h4>
   <ul>
    <li>Addiction</li>
    <li>Autism</li>
    <li>Art Therapy</li>
   </ul>
   </div>
 </div>
 </div>

<div class="container">
<h3 class="directory">Need help finding services? Try this wizard!</h3>
  <script src="https://d3js.org/d3.v3.min.js"></script>

<script>

var categories = [
  {
    "name": "Which Services do you need?",
    "parent": "null",
    "value": 105,
    "type": "#72b8c9",
    "level": "#72b8c9",
    "children": [
      {
        "name": "Education",
        "parent": "Which Services do you need?",
        "value": 60,
        "type": "#fed3a5",
        "level": "#fed3a5",
        "children": [
                  {
                    "name": "Tutoring",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                  },
                  {
                    "name": "Mentoring",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                  },
                  {
                    "name": "ESL",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                  },
                  {
                    "name": "Special Needs",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                  }
        ]
      },
      {
        "name": "Health Services",
        "parent": "Which Services do you need?",
        "value": 60,
        "type": "#fed3a5",
        "level": "#fed3a5",
        "children": [
                    {
                    "name": "Medicine",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    },
                    {
                    "name": "Nutrition",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    },
        ]
      },

      {
        "name": "Mental Health",
        "parent": "Which Services do you need?",
        "value": 60,
        "type": "#fed3a5",
        "level": "#fed3a5",
        "children": [
                    {
                    "name": "Addiction",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    },
                    {
                    "name": "Counseling",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    },
                    {
                    "name": "Therapy",
                    "parent": "Education",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    "children": [
                                {
                                "name": "Group",
                                "parent": "Education",
                                "value": 40,
                                "type": "#fe5e31",
                                "level": "#fe5e31",
                                },
                                {
                                "name": "Peer2Peer",
                                "parent": "Education",
                                "value": 40,
                                "type": "#fe5e31",
                                "level": "#fe5e31",
                                }
                    ]
                    },
        ]
      },

      {
        "name": "Social Services",
        "parent": "Which Services do you need?",
        "value": 60,
        "type": "#fed3a5",
        "level": "#fed3a5",
        "children": [
                    {
                    "name": "Childcare",
                    "parent": "Social Services",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    },
                    {
                    "name": "Food",
                    "parent": "Social Services",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    },
                    {
                    "name": "Shelter",
                    "parent": "Social Services",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    },
                    {
                    "name": "Transportation",
                    "parent": "Social Services",
                    "value": 50,
                    "type": "#fe9001",
                    "level": "#fe9001",
                    }
        ]
      },
    ]
  }
];


// ************** Generate the tree diagram  *****************
var margin = {top: 10, right: 120, bottom: 10, left: 220},
  width = 960 - margin.right - margin.left,
  height = 700 - margin.top - margin.bottom;

var i = 0,
  duration = 750,
  root;

var tree = d3.layout.tree()
  .size([height, width]);

var diagonal = d3.svg.diagonal()
  .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("body").append("svg")
  .attr("width", width + margin.right + margin.left)
  .attr("height", height + margin.top + margin.bottom)
  .append("g")
  .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

root = categories[0];
root.x0 = height / 2;
root.y0 = width/2;

var nodes = flatten(root);
nodes.forEach(function(d) {
  d._children = d.children;
  d.children = null;
});

// Updated this to the flatten function()
//root.children.forEach(click);
// collapse all upon load
//click(root);

update(root);


d3.select(self.frameElement).style("height", "500px");

// Returns a list of all nodes under the root.
function flatten(root) {
  var nodes = [], i = 0;

  function recurse(node) {
    if (node.children) node.children.forEach(recurse);
    if (!node.id) node.id = ++i;
    nodes.push(node);
  }

  recurse(root);
  return nodes;
}

function update(source) {

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
    links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d) { d.y = d.depth * 180; });

  // Update the nodes…
  var node = svg.selectAll("g.node")
    .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
    .attr("class", "node")
    .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
    .on("click", click);

  nodeEnter.append("circle")
   .attr("r", function(d) { return d.value; })
   .style("stroke", function(d) { return d.type; })
   .style("fill", "#fff");

  nodeEnter.append("text")
    .attr("x", 0)
    .attr("dy", ".35em")
    .attr("text-anchor", "middle")
    .text(function(d) { return d.name; });

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
    .duration(duration)
    .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
   .attr("r", function(d) { return d.value; })
   .style("stroke", function(d) { return d.type; })
   .style("fill", function(d) { return d.level; });

  nodeUpdate.select("text")
    .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position.
  var nodeExit = node.exit().transition()
    .duration(duration)
    .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
    .remove();

  nodeExit.select("circle")
    .attr("r", 1e-6);

  nodeExit.select("text")
    .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
    .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position.
  link.enter().insert("path", "g")
    .attr("class", "link")
    .attr("d", function(d) {
    var o = {x: source.x0, y: source.y0};
    return diagonal({source: o, target: o});
    });

  // Transition links to their new position.
  link.transition()
    .duration(duration)
    .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position.
  link.exit().transition()
    .duration(duration)
    .attr("d", function(d) {
    var o = {x: source.x, y: source.y};
    return diagonal({source: o, target: o});
    })
    .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
  d.x0 = d.x;
  d.y0 = d.y;
  });

}

// Toggle children on click.
function click(d) {
  if (d.children) {
  d._children = d.children;
  d.children = null;
  } else {
  d.children = d._children;
  d._children = null;
  }
  update(d);
}

</script>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="col-lg-6 col-md-6 col-sm-12">
      <span class='st_sharethis_large' displayText='ShareThis'></span>
      <span class='st_facebook_large' displayText='Facebook'></span>
      <span class='st_twitter_large' displayText='Tweet'></span>
      <span class='st_linkedin_large' displayText='LinkedIn'></span>
      <span class='st_pinterest_large' displayText='Pinterest'></span>
      <span class='st_email_large' displayText='Email'></span>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 copyright">
    &copy; 2016 City of St. Petersburg
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar-header">
  <a class="navbar-brand" href="<%= root_path %>" data-no-turbolink="true">
    <p>Home</p>
  </a>
</div>
<ul class="nav navbar-nav navbar-left">
  <li>
    <%= link_to "About", about_path, class:'root-link-nav', :"data-no-turbolink" => true %>
  </li>
  <li>
    <%= link_to "Privacy", privacy_path, class:'root-link-nav', :"data-no-turbolink" => true %>
  </li>
  <li>
    <%= link_to "All Providers", providers_path, :"data-no-turbolink" => true %>
  </li>
</ul>
<div class="navbar-right">
  <%= link_to "Register as a Provider", new_provider_path, class: "btn btn-primary navbar-btn", :"data-no-turbolink" => true %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SPFS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  	<script type="text/javascript">var switchTo5x=true;</script>
	<script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript">stLight.options({publisher: "e1e3e7e7-862c-4d80-96e1-2e7f5780a6b3", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

</head>
<body>
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <%= render 'layouts/navbar' %>
    </div>
  </div>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <h2>Business Information</h2>
      <div class="form-group">
        <%= f.label :businessname %><br>
        <%= f.text_field :businessname, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :firstname %><br>
        <%= f.text_field :firstname, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :lastname %><br>
        <%= f.text_field :lastname, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phonenumber %><br>
        <%= f.text_field :phonenumber, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <h2>Address</h2>
      <div class="form-group">
        <%= f.label :street %><br>
        <%= f.text_field :street, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city %><br>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :state %><br>
        <%= f.text_field :state, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :zip %><br>
        <%= f.text_field :zip, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2>Additional Information</h2>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_area :description, rows: 4,class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :url %><br>
          <%= f.text_field :url, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :provider_type %><br>
          <%= f.text_field :provider_type, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :active %><br>
          <%= f.check_box :active %>
        </div>
        <div class="actions">
          <%= f.submit "Register", class: "btn btn-primary"%>
        </div>
      </div>
    </div>
  </div>



<% end %>

app/views/providers/edit.html.erb
<div class="container">
  <h1>Editing Provider</h1>
  <br/>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= render 'form' %>
      <%= link_to 'Show', @provider %> |
      <%= link_to 'Back', providers_path %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/providers/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="header">
    <h1>Providers</h1>
  </div>
  <br/>
  <div class="provider_index">
    <% @providers.in_groups_of(4, false) do |providers| %>
      <div class="row">
        <% providers.each do |provider| %>
          <div class="col-md-3 main_theme_layout member_index_layout">
            <h4><%= provider.businessname %></h4>
            <h5>><%= provider.phonenumber %>, <%= provider.email %></h5>
            <h5><%= provider.street %><br>
                <%= provider.city %> <%= provider.state %>, <%= provider.zip %></h5>
            <p><%= provider.description %></p>
            <p><%= link_to "website", provider.url, class: "btn btn-primary"%></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
</div>

app/views/providers/new.html.erb
<div class="container">
  <h1>New Provider</h1>
  <br/>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= render 'form' %>
      <%= link_to 'Back', providers_path %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/providers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Businessname:</strong>
        <%= @provider.businessname %>
      </p>

      <p>
        <strong>Firstname:</strong>
        <%= @provider.firstname %>
      </p>

      <p>
        <strong>Lastname:</strong>
        <%= @provider.lastname %>
      </p>

      <p>
        <strong>Phonenumber:</strong>
        <%= @provider.phonenumber %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @provider.email %>
      </p>

      <p>
        <strong>Street:</strong>
        <%= @provider.street %>
      </p>

      <p>
        <strong>City:</strong>
        <%= @provider.city %>
      </p>

      <p>
        <strong>State:</strong>
        <%= @provider.state %>
      </p>

      <p>
        <strong>Zip:</strong>
        <%= @provider.zip %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @provider.description %>
      </p>

      <p>
        <strong>Url:</strong>
        <%= @provider.url %>
      </p>

      <p>
        <strong>Active:</strong>
        <%= @provider.active %>
      </p>

      <%= link_to 'Edit', edit_provider_path(@provider) %> |
      <%= link_to 'Back', providers_path %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>